### ISSUE TITLE
作业

### ISSUE THREAD

**Issue by dongpoyezi** [GeekUniversity/Frontend-02-Template#12]
#学号:G20200447020112
#姓名:叶长根
#班级:2班
#小组:2组
#作业&总结链接:https://github.com/dongpoyezi/Frontend-02-Template/tree/master/week01

**Comment by liuweiqiang316** [comment]
同学你作业提交错位置了,week01的作业应该提交到这里:https://github.com/GeekUniversity/Frontend-02-Template/issues/1
