### ISSUE TITLE
week01作业提交

### ISSUE THREAD

**Issue by EWL0829** [GeekUniversity/Frontend-02-Template#16]
#学号: G20200447020316
#姓名: 李月
#班级: 2期2班
#小组: 4组
#作业&总结链接: https://github.com/EWL0829/Frontend-02-Template/tree/master/week01

**Comment by ghost** [comment]
#学号: G20200447020148
#姓名: 于良骥
#班级: 2期2班
#小组: 4组
#作业&总结链接: https://github.com/yuliangji/Frontend-02-Template/tree/master/week01

**Comment by baooab** [comment]
#学号: G20200343050335
#姓名: 张宝
#班级: 2期1班
#小组: 9组
#作业&总结链接: https://github.com/baooab/Frontend-02-Template/tree/master/week01

**Comment by GeekUniversity** [comment]
同学你提交错了，去置顶的issue那里进行comment，不要新建issue

**Comment by ghost** [comment]
我是在这里提交的啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"GeekUniversity"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 下午5:20
收件人:&nbsp;"GeekUniversity/Frontend-02-Template"<Frontend-02-Template@noreply.github.com&gt;;
抄送:&nbsp;"于良骥"<260447427@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [GeekUniversity/Frontend-02-Template] week01作业提交 (#16)





 
同学你提交错了，去置顶的issue那里进行comment，不要新建issue
