### ISSUE TITLE
第一周作业

### ISSUE THREAD

**Issue by JimmyFok** [GeekUniversity/Frontend-02-Template#44]
#学号：G20200447020423
#姓名：霍俊敏
#班级：1班
#小组：5组
#作业&链接总结：https://github.com/jimmyfok/Frontend-02-Template

**Comment by Huang-Hash-Brown** [comment]
#学号:G20200447020388
#姓名: 周煌
#班级:2班
#小组:6组
#作业&总结链接:https://github.com/freshment/Frontend-02-Template/tree/master/week01
